### ISSUE TITLE
Multi-hop

### ISSUE THREAD

**Issue by micBona** [LuisEduardoUnifesp/ESDWSNforArduino#1]
Hello,
first of all, I'd like to thank you for this library and for your contribution on SD-WSN topic.
I read the paper in which the ESDWSN is presented and in the Experimental Performance Evaluation section the solution has been tested on a star topology.
Can this library also be applied to multi-hop topologies? 
For my understanding the answer should be yes but maybe I'm wrong.

Thank you in advance

**Comment by LuisEduardoUnifesp** [comment]
The library is programmed to work in multi-hop, however, due to the restrictions of the test environment and the time to finish my PhD, I was not able to carry out the tests to validate it.

**Comment by micBona** [comment]
Ok, thank you for the kind and quick response.
I'll close the issue.
